import { CourseRow, Snapshot } from "./api";

// Offline demo dataset.
//
// This snapshot lets anyone — including a store reviewer without an SJTU
// JAccount and off the campus network — launch the app, skip login, and
// exercise the full workbench with believable sample data. All values here are
// fabricated for preview only; the shape mirrors what gui_backend.build_snapshot
// produces so the UI renders identically. Demo mode never touches real state
// files and disables every network/write action.

function course(row: CourseRow): CourseRow {
  return row;
}

const courses: CourseRow[] = [
  course({
    jxb_id: "DEMO-EN-01",
    title: "学术英语写作",
    class_name: "01班",
    summary: "李明 · 周一第3-4节 · 已满",
    detail: "李明 · 周一第3-4节{1-16周} · 东上院301 · 通识核心",
    teachers: "李明",
    schedule: ["星期一第3-4节{1-16周}"],
    locations: ["东上院301"],
    search_text: "学术英语写作 李明 ENGL1201 01班 通识核心",
    seat_text: "60 / 60",
    availability: "full",
    availability_text: "已满",
    group: "英语拓展",
    chosen: false,
    category: "通识核心",
    rating_text: "4.6 · 128 评价",
    rating: {
      status: "rated",
      score: 4.6,
      count: 128,
      teacher: "李明",
      semester: "2024-2025-1",
      updated_at: "2026-07-20 08:00:00",
      message: null,
    },
    kch: "ENGL1201",
    sksj: "星期一第3-4节{1-16周}",
  }),
  course({
    jxb_id: "DEMO-EN-02",
    title: "学术英语写作",
    class_name: "02班",
    summary: "王芳 · 周三第3-4节 · 有空位",
    detail: "王芳 · 周三第3-4节{1-16周} · 东上院302 · 通识核心",
    teachers: "王芳",
    schedule: ["星期三第3-4节{1-16周}"],
    locations: ["东上院302"],
    search_text: "学术英语写作 王芳 ENGL1201 02班 通识核心",
    seat_text: "48 / 60",
    availability: "open",
    availability_text: "有空位",
    group: "英语拓展",
    chosen: true,
    category: "通识核心",
    rating_text: "4.2 · 86 评价",
    rating: {
      status: "rated",
      score: 4.2,
      count: 86,
      teacher: "王芳",
      semester: "2024-2025-1",
      updated_at: "2026-07-20 08:00:00",
      message: null,
    },
    kch: "ENGL1201",
    sksj: "星期三第3-4节{1-16周}",
  }),
  course({
    jxb_id: "DEMO-CS-01",
    title: "数据结构",
    class_name: "03班",
    summary: "张伟 · 周二第1-2节 · 有空位",
    detail: "张伟 · 周二第1-2节{1-16周} · 电信群楼3-200 · 专业基础",
    teachers: "张伟",
    schedule: ["星期二第1-2节{1-16周}"],
    locations: ["电信群楼3-200"],
    search_text: "数据结构 张伟 CS0501 03班 专业基础",
    seat_text: "112 / 150",
    availability: "open",
    availability_text: "有空位",
    group: null,
    chosen: false,
    category: "专业基础",
    rating_text: "4.8 · 210 评价",
    rating: {
      status: "rated",
      score: 4.8,
      count: 210,
      teacher: "张伟",
      semester: "2024-2025-1",
      updated_at: "2026-07-20 08:00:00",
      message: null,
    },
    kch: "CS0501",
    sksj: "星期二第1-2节{1-16周}",
  }),
  course({
    jxb_id: "DEMO-PH-01",
    title: "大学物理(II)",
    class_name: "01班",
    summary: "陈静 · 周四第5-6节 · 已满",
    detail: "陈静 · 周四第5-6节{1-16周} · 东中院1-105 · 专业基础",
    teachers: "陈静",
    schedule: ["星期四第5-6节{1-16周}"],
    locations: ["东中院1-105"],
    search_text: "大学物理 陈静 PHY1202 01班 专业基础",
    seat_text: "90 / 90",
    availability: "full",
    availability_text: "已满",
    group: null,
    chosen: true,
    category: "专业基础",
    rating_text: "暂无评价",
    rating: {
      status: "empty",
      score: 0,
      count: 0,
      teacher: null,
      semester: "2024-2025-1",
      updated_at: "2026-07-20 08:00:00",
      message: null,
    },
    kch: "PHY1202",
    sksj: "星期四第5-6节{1-16周}",
  }),
  course({
    jxb_id: "DEMO-PE-01",
    title: "篮球",
    class_name: "01班",
    summary: "赵强 · 周五第7-8节 · 有空位",
    detail: "赵强 · 周五第7-8节{1-16周} · 体育馆篮球场 · 体育",
    teachers: "赵强",
    schedule: ["星期五第7-8节{1-16周}"],
    locations: ["体育馆篮球场"],
    search_text: "篮球 赵强 PE0301 01班 体育",
    seat_text: "28 / 40",
    availability: "open",
    availability_text: "有空位",
    group: "体育项目",
    chosen: false,
    category: "体育",
    rating_text: "未收录",
    rating: {
      status: "not_found",
      score: null,
      count: null,
      teacher: null,
      semester: null,
      updated_at: null,
      message: "选课社区暂无该课程记录",
    },
    kch: "PE0301",
    sksj: "星期五第7-8节{1-16周}",
  }),
  course({
    jxb_id: "DEMO-PE-02",
    title: "羽毛球",
    class_name: "02班",
    summary: "孙丽 · 周三第7-8节 · 已满",
    detail: "孙丽 · 周三第7-8节{1-16周} · 体育馆羽毛球馆 · 体育",
    teachers: "孙丽",
    schedule: ["星期三第7-8节{1-16周}"],
    locations: ["体育馆羽毛球馆"],
    search_text: "羽毛球 孙丽 PE0307 02班 体育",
    seat_text: "36 / 36",
    availability: "full",
    availability_text: "已满",
    group: "体育项目",
    chosen: false,
    category: "体育",
    rating_text: "4.4 · 54 评价",
    rating: {
      status: "rated",
      score: 4.4,
      count: 54,
      teacher: "孙丽",
      semester: "2024-2025-1",
      updated_at: "2026-07-20 08:00:00",
      message: null,
    },
    kch: "PE0307",
    sksj: "星期三第7-8节{1-16周}",
  }),
];

export const demoSnapshot: Snapshot = {
  generated_at: "2026-07-20 08:00:00",
  metrics: {
    queries: 4,
    groups: 2,
    snapshot: 4,
    watched: 4,
    open_courses: 3,
    interval: "60-120s",
    auto_swap: "off",
  },
  settings: {
    jaccount_user: "demo",
    jaccount_pass: "",
    course_plus_password: "",
    has_jaccount_pass: false,
    has_course_plus_password: false,
    poll_min: 60,
    poll_max: 120,
    email_enabled: false,
    smtp_host: "mail.sjtu.edu.cn",
    smtp_port: 465,
    smtp_user: "",
    smtp_pass: "",
    has_smtp_pass: false,
    smtp_pass_fallback: true,
    secret_backend: "演示模式（不写入）",
    mail_from: "",
    mail_to: "",
  },
  onboarding: {
    completed: true,
    has_account: true,
    catalog_ready: true,
  },
  user: {
    name: "示例同学",
    student_id: "5240379000",
    class_name: "示例班级",
    major: "计算机科学与技术",
    term: "2024-2025-1",
    catalog_fetched_at: "2026-07-20 08:00:00",
  },
  groups: [
    {
      name: "英语拓展",
      is_pe: false,
      priority: ["DEMO-EN-01", "DEMO-EN-02"],
      held: "DEMO-EN-02",
      held_label: "学术英语写作 - 02班",
      watched_count: 2,
      fatal: false,
      members: [
        {
          jxb_id: "DEMO-EN-01",
          label: "学术英语写作 - 01班",
          detail: "李明 · 周一第3-4节 · 已满",
          chosen: false,
          watched: true,
          availability: "full",
        },
        {
          jxb_id: "DEMO-EN-02",
          label: "学术英语写作 - 02班",
          detail: "王芳 · 周三第3-4节 · 当前持有",
          chosen: true,
          watched: true,
          availability: "open",
        },
      ],
    },
    {
      name: "体育项目",
      is_pe: true,
      priority: ["DEMO-PE-01", "DEMO-PE-02"],
      held: null,
      held_label: "-",
      watched_count: 2,
      fatal: false,
      members: [
        {
          jxb_id: "DEMO-PE-01",
          label: "篮球 - 01班",
          detail: "赵强 · 周五第7-8节 · 有空位",
          chosen: false,
          watched: true,
          availability: "open",
        },
        {
          jxb_id: "DEMO-PE-02",
          label: "羽毛球 - 02班",
          detail: "孙丽 · 周三第7-8节 · 已满",
          chosen: false,
          watched: true,
          availability: "full",
        },
      ],
    },
  ],
  courses,
  state_rows: [
    {
      jxb_id: "DEMO-EN-01",
      watched: true,
      group: "英语拓展",
      title: "学术英语写作 - 01班",
      summary: "李明 · 周一第3-4节",
      seat_text: "60 / 60",
      open: false,
    },
    {
      jxb_id: "DEMO-EN-02",
      watched: true,
      group: "英语拓展",
      title: "学术英语写作 - 02班",
      summary: "王芳 · 周三第3-4节",
      seat_text: "48 / 60",
      open: true,
    },
    {
      jxb_id: "DEMO-PE-01",
      watched: true,
      group: "体育项目",
      title: "篮球 - 01班",
      summary: "赵强 · 周五第7-8节",
      seat_text: "28 / 40",
      open: true,
    },
    {
      jxb_id: "DEMO-PE-02",
      watched: true,
      group: "体育项目",
      title: "羽毛球 - 02班",
      summary: "孙丽 · 周三第7-8节",
      seat_text: "36 / 36",
      open: false,
    },
  ],
  swap_state: {
    completed: ["DEMO-EN-02"],
    fatal: [],
    fatal_groups: [],
  },
  swap_history: [
    {
      timestamp: "2026-07-20 09:15:00",
      dry_run: false,
      group: "英语拓展",
      target: "DEMO-EN-02",
      drop: "",
      ok: true,
      status: "success",
      kcmc: "学术英语写作",
    },
    {
      timestamp: "2026-07-19 22:40:00",
      dry_run: true,
      group: "体育项目",
      target: "DEMO-PE-01",
      drop: "DEMO-PE-02",
      ok: false,
      status: "演练：目标暂无空位",
      kcmc: "篮球",
    },
  ],
  logs: [
    "[changes] 2026-07-20 08:00:00 监控启动，加载 2 个方案 / 4 个教学班",
    "[changes] 2026-07-20 09:15:00 英语拓展：升级至更高优先级教学班 学术英语写作-02班",
    "[changes] 2026-07-20 09:16:00 体育项目：篮球-01班 出现空位，等待下一轮换课",
  ],
  categories: ["专业基础", "体育", "通识核心"],
};
